"""
CIEL/Ω — N-Body Relational Green/Kepler Dynamics v0.2

STATUS:
    CONDITIONAL_EXACT_GEOMETRY + OPEN_TIR_BINDING

Core correction from v0.1:
    An inverse-distance potential is NOT dimension-independent.

If the relational interaction is generated by an isotropic conserved radial
flux / Green kernel of the intrinsic N-dimensional Laplacian, then:

    N = 2:
        V_N(r) = mu * log(r/r0)
        |F_N| ~ 1/r

    N > 2:
        V_N(r) = -mu / ((N-2) r^(N-2))
        |F_N| ~ 1/r^(N-1)

Therefore:
    N = 3 -> V(r) = -mu/r, |F| ~ 1/r^2

Kepler's inverse-distance potential emerges as the N=3 member of the
dimensionally derived family, rather than being assumed for arbitrary N.

Project-source relevance:
    - intrinsic tetrahedral depth is represented in Bloch ball B^3;
    - the Poincare disk is a 2D interference surface;
    - therefore B^3 and D^2 must not be conflated.

Epistemic firewall:
    Geometry of the N-dimensional radial flux law is exact conditional on
    the conserved-isotropic-flux / Laplace-field assumption.
    The claim that TIR relational coupling obeys that field equation remains OPEN.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Sequence, Tuple
import math
import numpy as np

@dataclass(frozen=True)
class RelationalBody:
    body_id: str
    position: np.ndarray
    velocity: np.ndarray
    inertia: float = 1.0

    def __post_init__(self):
        x=np.asarray(self.position,dtype=float)
        v=np.asarray(self.velocity,dtype=float)
        if x.ndim != 1 or v.ndim != 1 or x.shape != v.shape:
            raise ValueError("position and velocity must be equal-shaped 1D vectors")
        if x.size < 2:
            raise ValueError("intrinsic dimension must be >= 2")
        if self.inertia <= 0:
            raise ValueError("inertia must be positive")
        object.__setattr__(self,"position",x)
        object.__setattr__(self,"velocity",v)

    @property
    def dim(self) -> int:
        return int(self.position.size)

@dataclass(frozen=True)
class PairCoupling:
    i: int
    j: int
    mu: float

    def __post_init__(self):
        if self.i == self.j:
            raise ValueError("self coupling invalid")
        if self.mu < 0:
            raise ValueError("mu must be nonnegative")

def unit_sphere_area(dim_minus_one: int) -> float:
    N = int(dim_minus_one) + 1
    if N < 2:
        raise ValueError("N must be >= 2")
    return float(2.0 * math.pi**(N/2.0) / math.gamma(N/2.0))

def pair_displacement(a: RelationalBody, b: RelationalBody) -> np.ndarray:
    if a.dim != b.dim:
        raise ValueError("dimension mismatch")
    return b.position-a.position

def pair_distance(a: RelationalBody, b: RelationalBody) -> float:
    return float(np.linalg.norm(pair_displacement(a,b)))

def nd_green_potential_from_r(r: float, mu: float, N: int, *, r0: Optional[float]=None) -> float:
    r=float(r); mu=float(mu); N=int(N)
    if r <= 0:
        raise ValueError("r must be positive")
    if N < 2:
        raise ValueError("N must be >= 2")
    if N == 2:
        if r0 is None:
            r0=1.0
        if r0 <= 0:
            raise ValueError("r0 must be positive")
        return float(mu*math.log(r/float(r0)))
    return float(-mu/((N-2)*(r**(N-2))))

def nd_green_potential(a: RelationalBody, b: RelationalBody, mu: float, *, r0: Optional[float]=None) -> float:
    if a.dim != b.dim:
        raise ValueError("dimension mismatch")
    return nd_green_potential_from_r(pair_distance(a,b),mu,a.dim,r0=r0)

def inverse_distance_potential(a: RelationalBody, b: RelationalBody, mu: float) -> float:
    """Backward-compatible API name; literally inverse-distance only for N=3."""
    return nd_green_potential(a,b,mu)

def central_pair_force(a: RelationalBody, b: RelationalBody, mu: float) -> np.ndarray:
    rvec=pair_displacement(a,b)
    r=float(np.linalg.norm(rvec))
    if r == 0:
        raise ZeroDivisionError("relational collision/singularity")
    return float(mu)*rvec/(r**a.dim)

def radial_flux_invariant(force_magnitude: float, r: float, N: int) -> float:
    if r <= 0 or N < 2:
        raise ValueError
    return float(force_magnitude*unit_sphere_area(N-1)*(r**(N-1)))

def accelerations(bodies: Sequence[RelationalBody], couplings: Sequence[PairCoupling]) -> Tuple[np.ndarray,...]:
    if not bodies:
        return tuple()
    N=bodies[0].dim
    if any(b.dim!=N for b in bodies):
        raise ValueError("all bodies must share intrinsic dimension")
    F=[np.zeros(N,dtype=float) for _ in bodies]
    for c in couplings:
        if not (0 <= c.i < len(bodies) and 0 <= c.j < len(bodies)):
            raise IndexError("coupling body index")
        f=central_pair_force(bodies[c.i],bodies[c.j],c.mu)
        F[c.i]+=f
        F[c.j]-=f
    return tuple(F[i]/bodies[i].inertia for i in range(len(bodies)))

def bivector_angular_momentum(body: RelationalBody) -> np.ndarray:
    x=body.position; v=body.velocity
    return body.inertia*(np.outer(x,v)-np.outer(v,x))

def total_bivector_angular_momentum(bodies: Sequence[RelationalBody]) -> np.ndarray:
    if not bodies:
        return np.zeros((0,0))
    N=bodies[0].dim
    return sum((bivector_angular_momentum(b) for b in bodies),start=np.zeros((N,N)))

def kinetic_energy(bodies: Sequence[RelationalBody]) -> float:
    return float(sum(0.5*b.inertia*np.dot(b.velocity,b.velocity) for b in bodies))

def potential_energy(bodies: Sequence[RelationalBody], couplings: Sequence[PairCoupling]) -> float:
    return float(sum(nd_green_potential(bodies[c.i],bodies[c.j],c.mu) for c in couplings))

def total_energy(bodies, couplings) -> float:
    return kinetic_energy(bodies)+potential_energy(bodies,couplings)

@dataclass(frozen=True)
class DimensionalKeplerReport:
    N: int
    potential_scaling: str
    force_scaling: str
    kepler_inverse_distance: bool
    epistemic_status: str

def dimensional_report(N: int) -> DimensionalKeplerReport:
    N=int(N)
    if N<2:
        raise ValueError("N must be >=2")
    if N==2:
        return DimensionalKeplerReport(N,"log(r)","r^-1",False,"CONDITIONAL_EXACT_UNDER_ISOTROPIC_CONSERVED_FLUX")
    return DimensionalKeplerReport(N,f"r^{2-N}",f"r^{1-N}",N==3,"CONDITIONAL_EXACT_UNDER_ISOTROPIC_CONSERVED_FLUX")

@dataclass(frozen=True)
class AgencyState:
    volume: Optional[float]
    dimension: Optional[float]
    provenance: str
    def delta(self, other: "AgencyState") -> Optional[float]:
        if self.volume is None or other.volume is None:
            return None
        return float(other.volume-self.volume)

@dataclass(frozen=True)
class ConsentGeometry:
    admissible_projection_norm: Optional[float]
    residual_norm: Optional[float]
    alignment: Optional[float]
    status: str

def consent_geometry(actual_velocity: Sequence[float], admissible_basis: Optional[np.ndarray]) -> ConsentGeometry:
    v=np.asarray(actual_velocity,dtype=float).ravel()
    if admissible_basis is None:
        return ConsentGeometry(None,None,None,"UNKNOWN")
    B=np.asarray(admissible_basis,dtype=float)
    if B.ndim!=2 or B.shape[1]!=v.size:
        raise ValueError("admissible_basis shape")
    if B.shape[0]==0:
        proj=np.zeros_like(v)
    else:
        _,_,Vh=np.linalg.svd(B,full_matrices=False)
        rank=np.linalg.matrix_rank(B)
        Q=Vh[:rank].T
        proj=Q@(Q.T@v) if rank else np.zeros_like(v)
    residual=v-proj
    nv=float(np.linalg.norm(v))
    return ConsentGeometry(float(np.linalg.norm(proj)),float(np.linalg.norm(residual)),None if nv==0 else float(np.linalg.norm(proj)/nv),"DERIVED")

@dataclass(frozen=True)
class InformationState:
    covariance: np.ndarray
    def __post_init__(self):
        c=np.asarray(self.covariance,dtype=float)
        if c.ndim!=2 or c.shape[0]!=c.shape[1]:
            raise ValueError("covariance must be square")
        object.__setattr__(self,"covariance",c)
    def uncertainty_volume_logdet(self) -> Optional[float]:
        sign,ld=np.linalg.slogdet(self.covariance)
        return None if sign<=0 else float(ld)

def information_asymmetry(a: InformationState,b: InformationState) -> Optional[float]:
    ua=a.uncertainty_volume_logdet(); ub=b.uncertainty_volume_logdet()
    if ua is None or ub is None:
        return None
    return float(ua-ub)

__all__=[
    "RelationalBody","PairCoupling","unit_sphere_area","pair_displacement","pair_distance",
    "nd_green_potential_from_r","nd_green_potential","inverse_distance_potential","central_pair_force",
    "radial_flux_invariant","accelerations","bivector_angular_momentum","total_bivector_angular_momentum",
    "kinetic_energy","potential_energy","total_energy","DimensionalKeplerReport","dimensional_report",
    "AgencyState","ConsentGeometry","consent_geometry","InformationState","information_asymmetry",
]
