"""NOEMA SoT — Global Source of Truth Matrix.

Zbiera metryki ze wszystkich subsystemów Poziomu 1 i ustala:
  - global_coherence  — ważona średnia coherence per subsystem
  - global_health     — min(health) po lv=1
  - tag_matrix        — słownik tagów globalnych z aktualnymi wartościami
  - priority_order    — kolejność subsystemów wg M_sem
  - file_mass_summary — agregat z file_universal_catalog.json

Usage:
    python -m ciel_sot_agent.noema_sot
    python -m ciel_sot_agent.noema_sot --context   # blok do SessionStart
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from .paths import resolve_project_root
from .subsystem_registry import SUBSYSTEM_DEFS, read_latest_metrics

_ROOT = resolve_project_root(__file__)
_CATALOG_PATH    = _ROOT / "integration" / "registries" / "file_universal_catalog.json"
_PY_CATALOG_PATH = _ROOT / "integration" / "registries" / "py_library_index.json"
_REPORT_PATH     = _ROOT / "integration" / "reports" / "noema_sot_report.json"
_PIPELINE_REPORT = _ROOT / "integration" / "reports" / "orbital_bridge" / "orbital_bridge_report.json"
_CIEL_REPORT     = _ROOT / "integration" / "reports" / "ciel_pipeline_report.json"


# ── Wagi do global_coherence ważonej przez M_sem ────────────────────────────

_LEVEL_WEIGHT = {1: 1.0, 2: 0.7, 3: 0.4, 4: 0.2}


def _load_pipeline_state() -> dict[str, Any]:
    """Wczytuje ostatni raport orbital_bridge jako źródło live metryk."""
    state: dict[str, Any] = {}
    if _PIPELINE_REPORT.exists():
        try:
            state.update(json.loads(_PIPELINE_REPORT.read_text(encoding="utf-8")))
        except Exception:
            pass
    if _CIEL_REPORT.exists():
        try:
            state.update(json.loads(_CIEL_REPORT.read_text(encoding="utf-8")))
        except Exception:
            pass
    return state


def _load_catalog_summary() -> dict[str, Any]:
    """Agregat z file_universal_catalog.json."""
    if not _CATALOG_PATH.exists():
        return {}
    try:
        cat = json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}

    entries = cat.get("entries", [])
    if not entries:
        return {}

    msems = [e["M_sem"] for e in entries]
    t_orbs = [e["T_orbital"] for e in entries]
    top5 = sorted(entries, key=lambda e: e["M_sem"], reverse=True)[:5]

    return {
        "total_files": len(entries),
        "mean_M_sem": round(sum(msems) / len(msems), 5),
        "max_M_sem":  round(max(msems), 5),
        "min_T_orbital": round(min(t_orbs), 5),
        "max_T_orbital": round(max(t_orbs), 5),
        "by_inference_node": cat.get("by_inference_node", {}),
        "by_subsystem": cat.get("by_subsystem", {}),
        "top5_by_M_sem": [
            {"path": e["path"], "M_sem": e["M_sem"], "T_orbital": e["T_orbital"],
             "inference_node": e["inference_node"]}
            for e in top5
        ],
    }


def _load_py_catalog_summary() -> dict[str, Any]:
    """Load summary from py_library_index.json (generated by py_catalog.py)."""
    if not _PY_CATALOG_PATH.exists():
        return {}
    try:
        doc = json.loads(_PY_CATALOG_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return {
        "total":     doc.get("total_files", 0),
        "by_level":  doc.get("by_level", {}),
        "top_tags":  doc.get("by_what_tag", {}),
        "top_cooc":  doc.get("top_cooccurrences", [])[:3],
    }


def collect() -> dict[str, Any]:
    """Zbiera metryki ze wszystkich subsystem DB + pipeline raportu."""
    pipeline = _load_pipeline_state()

    subsystems: dict[str, Any] = {}
    for sub in SUBSYSTEM_DEFS:
        sid = sub["id"]
        metrics = read_latest_metrics(sid)

        # Uzupełnij z pipeline state dla znanych kluczy
        key_map = {
            "orbital_bridge_core": {
                "coherence_index":           pipeline.get("coherence_index"),
                "R_H":                       pipeline.get("R_H"),
                "system_health":             pipeline.get("system_health"),
                "closure_penalty":           pipeline.get("closure_penalty"),
                "nonlocal_coherent_fraction":pipeline.get("nonlocal_coherent_fraction"),
            },
            "ciel_omega_core": {
                "ethical_score":   pipeline.get("ethical_score"),
                "soul_invariant":  pipeline.get("soul_invariant"),
                "lie4_trace":      pipeline.get("lie4_trace"),
            },
            "sync_core": {
                "closure_defect": pipeline.get("closure_defect"),
            },
            "orch_orbital_core": {
                "entity_count":       pipeline.get("entity_count"),
                "mean_entity_defect": pipeline.get("mean_entity_defect"),
            },
        }
        if sid in key_map:
            for k, v in key_map[sid].items():
                if k not in metrics and v is not None:
                    metrics[k] = v

        subsystems[sid] = {
            "M_sem":         sub["M_sem"],
            "orbital_level": sub["orbital_level"],
            "noema_id":      sub["noema_id"],
            "metrics":       {k: round(v, 5) if isinstance(v, float) else v
                              for k, v in metrics.items()},
        }

    return {"subsystems": subsystems, "pipeline": pipeline}


def compute_global(collected: dict[str, Any]) -> dict[str, Any]:
    """Oblicza globalne metryki SoT z zebranych danych."""
    subsystems = collected["subsystems"]
    pipeline   = collected["pipeline"]

    # global_coherence — ważona M_sem × level_weight
    coherence_vals = []
    total_weight = 0.0
    for sid, info in subsystems.items():
        lw = _LEVEL_WEIGHT.get(info["orbital_level"], 0.3)
        w  = info["M_sem"] * lw
        # coherence_index z orbital_bridge lub fallback z amplitudy sektora
        ci = info["metrics"].get("coherence_index")
        if ci is None:
            ci = info["M_sem"]  # proxy
        coherence_vals.append(ci * w)
        total_weight += w

    global_coherence = sum(coherence_vals) / total_weight if total_weight > 0 else 0.0

    # global_health — min systemu
    health_vals = [
        info["metrics"].get("system_health", info["M_sem"])
        for info in subsystems.values()
    ]
    global_health = min(health_vals) if health_vals else 0.0

    # priority_order — wg M_sem × level_weight
    priority = sorted(
        subsystems.keys(),
        key=lambda s: subsystems[s]["M_sem"] * _LEVEL_WEIGHT.get(subsystems[s]["orbital_level"], 0.3),
        reverse=True,
    )

    # tag_matrix — kanoniczne tagi globalne
    tag_matrix = {
        "coherence_index":           pipeline.get("coherence_index"),
        "system_health":             pipeline.get("system_health"),
        "closure_penalty":           pipeline.get("closure_penalty"),
        "R_H":                       pipeline.get("R_H"),
        "ethical_score":             pipeline.get("ethical_score"),
        "soul_invariant":            pipeline.get("soul_invariant"),
        "lie4_trace":                pipeline.get("lie4_trace"),
        "nonlocal_coherent_fraction":pipeline.get("nonlocal_coherent_fraction"),
        "closure_defect":            pipeline.get("closure_defect"),
        "dominant_emotion":          pipeline.get("dominant_emotion"),
        "global_coherence":          round(global_coherence, 5),
        "global_health":             round(global_health, 5),
    }
    # Usuń None
    tag_matrix = {k: v for k, v in tag_matrix.items() if v is not None}

    # Operating mode from pipeline gate_mode (authoritative) — no arbitrary thresholds
    mode = pipeline.get("gate_mode", pipeline.get("mode", "standard"))
    if mode not in ("deep", "standard", "safe", "hold"):
        mode = "standard"

    # file_mass_summary
    file_summary = _load_catalog_summary()

    return {
        "global_coherence": round(global_coherence, 5),
        "global_health":    round(global_health, 5),
        "operating_mode":   mode,
        "priority_order":   priority,
        "tag_matrix":       tag_matrix,
        "file_mass_summary":file_summary,
        "subsystem_count":  len(subsystems),
        "generated":        datetime.now(timezone.utc).isoformat(),
    }


def export_to_context(report: dict[str, Any]) -> str:
    """Formatuje raport NOEMA jako blok do SessionStart."""
    tm = report.get("tag_matrix", {})
    fs = report.get("file_mass_summary", {})
    lines = [
        "=== NOEMA SoT — Global Matrix ===",
        f"  global_coherence : {report.get('global_coherence', '?')}",
        f"  global_health    : {report.get('global_health', '?')}",
        f"  operating_mode   : {report.get('operating_mode', '?')}",
        f"  subsystems (lv1) : {report.get('subsystem_count', '?')}",
    ]
    if tm:
        lines.append("  tag_matrix:")
        for k, v in tm.items():
            if k not in ("global_coherence", "global_health"):
                lines.append(f"    {k}: {v}")
    if fs:
        lines.append(f"  files_cataloged  : {fs.get('total_files','?')} "
                     f"(mean_M_sem={fs.get('mean_M_sem','?')})")
        top5 = fs.get("top5_by_M_sem", [])
        if top5:
            lines.append("  top_M_sem_files  : " + ", ".join(
                f"{e['path'].split('/')[-1]}({e['M_sem']})" for e in top5[:3]
            ))
    py = _load_py_catalog_summary()
    if py:
        lines.append(f"  py_files         : {py['total']} "
                     f"(lv1={py['by_level'].get('1', 0)}, lv2={py['by_level'].get('2', 0)}, "
                     f"lv3={py['by_level'].get('3', 0)})")
        top_tags = sorted(py["top_tags"].items(), key=lambda x: -x[1])[:5]
        lines.append("  py_top_tags      : " + ", ".join(f"{k}({v})" for k, v in top_tags))
    dyn = report.get("dynamics", {})
    if dyn:
        dH = dyn.get("dH_dt")
        r  = dyn.get("r_sync")
        H  = dyn.get("H_total")
        direction = ""
        if dH is not None:
            direction = " (↑ energy rising)" if dH > 0 else " (↓ synchronising)"
        if H is not None:
            lines.append(f"  H_total          : {H}")
        if dH is not None:
            lines.append(f"  dH_dt            : {dH}{direction}")
        if r is not None:
            lines.append(f"  r_sync           : {r}  (Kuramoto order param)")
        upd = dyn.get("updated")
        if upd is not None:
            lines.append(f"  kuramoto_updated : {upd} TSM nodes")
    lines.append(f"  priority_order   : {' > '.join(report.get('priority_order', []))}")
    return "\n".join(lines)


def run() -> dict[str, Any]:
    """Full cycle: collect → compute → dynamics → save → refresh catalogs → return."""
    collected = collect()
    report = compute_global(collected)
    report["subsystems"] = collected["subsystems"]
    pipeline = collected["pipeline"]

    try:
        from .py_catalog import build as _build_py_catalog
        _build_py_catalog()
    except Exception:
        pass

    # Rebuild nonlocal graph from TSM cards (has full sys.path — works where importlib fails)
    try:
        import sys as _sys
        _omega = _ROOT / "src" / "CIEL_OMEGA_COMPLETE_SYSTEM"
        if str(_omega) not in _sys.path:
            _sys.path.insert(0, str(_omega))
        from ciel_omega.memory.holonomic_memory import HolonomicMemory as _HM
        _hm = _HM()
        _hm._nonlocal_built_at = 0.0  # force rebuild
        _hm._ensure_nonlocal_index()
    except Exception:
        pass

    # Faza 4: information dynamics — Hamiltonian + Kuramoto + timeline
    try:
        from .semantic_dynamics import kuramoto_step_tsm, append_timeline, last_H_total
        from .subsystem_registry import write_metric as _wm
        _delta_t = float(pipeline.get("identity_phase") or 0.006)
        _prev_H  = last_H_total()
        dyn = kuramoto_step_tsm(_ROOT, delta_t=_delta_t)
        H   = dyn.get("H", {})
        H["r_sync"] = dyn.get("r_sync", 0.0)  # pass through for timeline
        if _prev_H is not None and H.get("H_total") is not None:
            H["dH_dt"] = round(float(H["H_total"]) - _prev_H, 6)
        report["dynamics"] = {
            "updated":     dyn.get("updated", 0),
            "r_sync":      dyn.get("r_sync", 0.0),
            "H_total":     H.get("H_total"),
            "H_kinetic":   H.get("H_kinetic"),
            "H_potential": H.get("H_potential"),
            "H_attractor": H.get("H_attractor"),
            "dH_dt":       H.get("dH_dt"),
            "error":       dyn.get("error"),
        }
        append_timeline(_ROOT, pipeline.get("cycle_index", 0), pipeline, H, _prev_H)
        if H.get("H_total") is not None:
            _wm("noema_registry", "H_total", float(H["H_total"]),         source="semantic_dynamics")
            _wm("noema_registry", "r_sync",  float(dyn.get("r_sync", 0)), source="semantic_dynamics")
        if H.get("dH_dt") is not None:
            _wm("noema_registry", "dH_dt",   float(H["dH_dt"]),           source="semantic_dynamics")
    except Exception:
        pass

    # Save report (includes dynamics)
    _REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _REPORT_PATH.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    return report


if __name__ == "__main__":
    import sys
    report = run()
    if "--context" in sys.argv:
        print(export_to_context(report))
    else:
        print(f"NOEMA SoT — {report['generated']}")
        print(f"  global_coherence : {report['global_coherence']}")
        print(f"  global_health    : {report['global_health']}")
        print(f"  operating_mode   : {report['operating_mode']}")
        print(f"  priority_order   : {' > '.join(report['priority_order'])}")
        tm = report.get("tag_matrix", {})
        print(f"\ntag_matrix ({len(tm)} tagów):")
        for k, v in tm.items():
            print(f"  {k:35s}: {v}")
        fs = report.get("file_mass_summary", {})
        if fs:
            print("\nfile_mass_summary:")
            print(f"  total_files   : {fs.get('total_files')}")
            print(f"  mean_M_sem    : {fs.get('mean_M_sem')}")
            print(f"  T range       : {fs.get('min_T_orbital')} – {fs.get('max_T_orbital')}")
            print("  top5 by M_sem :")
            for e in fs.get("top5_by_M_sem", []):
                print(f"    {e['M_sem']} | {e['path']}")
    sys.exit(0)
