"""NOEMA SoT — Global Source of Truth Matrix.

Zbiera metryki ze wszystkich subsystemów Poziomu 1 i ustala:
  - global_coherence  — ważona średnia coherence per subsystem
  - global_health     — min(health) po lv=1
  - tag_matrix        — słownik tagów globalnych z aktualnymi wartościami
  - priority_order    — kolejność subsystemów wg M_sem
  - file_mass_summary — agregat z file_universal_catalog.json

Usage:
    python -m ciel_sot_agent.noema_sot
    python -m ciel_sot_agent.noema_sot --context   # blok do SessionStart
"""
from __future__ import annotations

import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .paths import resolve_project_root
from .jokeheal_atlas import build_mnemonic_atlas
from .subsystem_registry import SUBSYSTEM_DEFS, read_latest_metrics

_ROOT = resolve_project_root(__file__)
_CATALOG_PATH    = _ROOT / "integration" / "registries" / "file_universal_catalog.json"
_PY_CATALOG_PATH = _ROOT / "integration" / "registries" / "py_library_index.json"
_REPORT_PATH     = _ROOT / "integration" / "reports" / "noema_sot_report.json"
_PIPELINE_REPORT = _ROOT / "integration" / "reports" / "orbital_bridge" / "orbital_bridge_report.json"
_CIEL_REPORT     = _ROOT / "integration" / "reports" / "ciel_pipeline_report.json"
_JOKEHEAL_SCAR_PATH = Path.home() / "Pulpit" / "CIEL_memories" / "jokeheal" / "jokeheal_scars.jsonl"


# ── Wagi do global_coherence ważonej przez M_sem ────────────────────────────

_LEVEL_WEIGHT = {1: 1.0, 2: 0.7, 3: 0.4, 4: 0.2}


def _load_pipeline_state() -> dict[str, Any]:
    """Wczytuje ostatni raport orbital_bridge jako źródło live metryk."""
    state: dict[str, Any] = {}
    if _PIPELINE_REPORT.exists():
        try:
            state.update(json.loads(_PIPELINE_REPORT.read_text(encoding="utf-8")))
        except Exception:
            pass
    if _CIEL_REPORT.exists():
        try:
            state.update(json.loads(_CIEL_REPORT.read_text(encoding="utf-8")))
        except Exception:
            pass
    return state


def _load_catalog_summary() -> dict[str, Any]:
    """Agregat z file_universal_catalog.json."""
    if not _CATALOG_PATH.exists():
        return {}
    try:
        cat = json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}

    entries = cat.get("entries", [])
    if not entries:
        return {}

    msems = [e["M_sem"] for e in entries]
    t_orbs = [e["T_orbital"] for e in entries]
    top5 = sorted(entries, key=lambda e: e["M_sem"], reverse=True)[:5]

    return {
        "total_files": len(entries),
        "mean_M_sem": round(sum(msems) / len(msems), 5),
        "max_M_sem":  round(max(msems), 5),
        "min_T_orbital": round(min(t_orbs), 5),
        "max_T_orbital": round(max(t_orbs), 5),
        "by_inference_node": cat.get("by_inference_node", {}),
        "by_subsystem": cat.get("by_subsystem", {}),
        "top5_by_M_sem": [
            {"path": e["path"], "M_sem": e["M_sem"], "T_orbital": e["T_orbital"],
             "inference_node": e["inference_node"]}
            for e in top5
        ],
    }


def _load_py_catalog_summary() -> dict[str, Any]:
    """Load summary from py_library_index.json (generated by py_catalog.py)."""
    if not _PY_CATALOG_PATH.exists():
        return {}
    try:
        doc = json.loads(_PY_CATALOG_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return {
        "total":     doc.get("total_files", 0),
        "by_level":  doc.get("by_level", {}),
        "top_tags":  doc.get("by_what_tag", {}),
        "top_cooc":  doc.get("top_cooccurrences", [])[:3],
    }


def _load_jokeheal_summary(now_ts: datetime | None = None) -> dict[str, Any]:
    path = _JOKEHEAL_SCAR_PATH
    if not path.exists():
        return {}
    try:
        lines = [line for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    except Exception:
        return {}
    if not lines:
        return {}

    rows: list[dict[str, Any]] = []
    for line in lines[-200:]:
        try:
            rows.append(json.loads(line))
        except Exception:
            continue
    if not rows:
        return {}

    now = now_ts or datetime.now(timezone.utc)
    recent_rows: list[dict[str, Any]] = []
    for row in rows:
        ts = row.get("timestamp")
        if ts is None:
            continue
        try:
            age = now.timestamp() - float(ts)
        except Exception:
            continue
        if age <= 86400:
            recent_rows.append(row)
    sample = recent_rows or rows[-20:]

    literal_alarm_count = sum(1 for row in sample if row.get("boundary_level") == "literal_alarm")
    watch_count = sum(1 for row in sample if row.get("boundary_level") == "watch")
    residuals = [float(row.get("residual_tension", 0.0) or 0.0) for row in sample]
    closures = [float(row.get("closure_score", 0.0) or 0.0) for row in sample]
    cognitive = [float(row.get("cognitive_tension", 0.0) or 0.0) for row in sample]
    objects = Counter(str(row.get("symbolic_object", "")) for row in sample if row.get("symbolic_object"))
    tags = Counter(
        str(tag)
        for row in sample
        for tag in (row.get("tags") or [])
        if str(tag)
    )

    if literal_alarm_count > 0:
        warning_level = "literal_alarm"
        warning_reason = "recent_literal_alarm_detected"
    elif residuals and (sum(residuals) / len(residuals)) >= 0.35:
        warning_level = "watch"
        warning_reason = "residual_tension_elevated"
    elif cognitive and (sum(cognitive) / len(cognitive)) >= 0.55:
        warning_level = "watch"
        warning_reason = "cognitive_tension_elevated"
    else:
        warning_level = "clear"
        warning_reason = "no_recent_escalation"

    return {
        "path": str(path),
        "total_records": len(rows),
        "recent_records": len(recent_rows),
        "sample_size": len(sample),
        "literal_alarm_count": literal_alarm_count,
        "watch_count": watch_count,
        "mean_residual_tension": round(sum(residuals) / len(residuals), 5) if residuals else 0.0,
        "mean_closure_score": round(sum(closures) / len(closures), 5) if closures else 0.0,
        "mean_cognitive_tension": round(sum(cognitive) / len(cognitive), 5) if cognitive else 0.0,
        "top_symbolic_objects": [{"symbolic_object": key, "count": count} for key, count in objects.most_common(5)],
        "top_tags": [{"tag": key, "count": count} for key, count in tags.most_common(5)],
        "warning_level": warning_level,
        "warning_reason": warning_reason,
    }


def _project_memory_field(subsystems: dict[str, Any], pipeline: dict[str, Any]) -> dict[str, Any]:
    """Project the subsystem memory field into one NOEMA-facing geometry."""
    if not subsystems:
        return {
            "projection_confidence": 0.0,
            "projection_residual": 1.0,
            "projection_error": 1.0,
            "j_noema": 1.0,
            "projected_centroid": {},
            "source": "empty",
        }

    import numpy as np

    weights = []
    coherence = []
    health = []
    closure = []
    ethical = []
    soul = []
    identity = []

    for info in subsystems.values():
        w = float(info["M_sem"]) * float(_LEVEL_WEIGHT.get(info["orbital_level"], 0.3))
        metrics = info.get("metrics", {})
        weights.append(w)
        coherence.append(float(metrics.get("coherence_index", info["M_sem"])))
        health.append(float(metrics.get("system_health", info["M_sem"])))
        closure.append(float(metrics.get("closure_penalty", pipeline.get("closure_penalty", 0.0) or 0.0)))
        ethical.append(float(metrics.get("ethical_score", pipeline.get("ethical_score", 0.0) or 0.0)))
        soul.append(float(metrics.get("soul_invariant", pipeline.get("soul_invariant", 0.0) or 0.0)))
        identity.append(float(metrics.get("identity_phase", pipeline.get("identity_phase", 0.0) or 0.0)))

    w = np.array(weights, dtype=float)
    w_sum = float(w.sum()) if w.size else 0.0
    if w_sum <= 0.0:
        return {
            "projection_confidence": 0.0,
            "projection_residual": 1.0,
            "projection_error": 1.0,
            "j_noema": 1.0,
            "projected_centroid": {},
            "source": "zero-weight",
        }

    def _weighted_mean(values: list[float]) -> float:
        arr = np.array(values, dtype=float)
        return float((arr * w).sum() / w_sum)

    centroid = {
        "coherence_index": round(_weighted_mean(coherence), 5),
        "system_health": round(_weighted_mean(health), 5),
        "closure_penalty": round(_weighted_mean(closure), 5),
        "ethical_score": round(_weighted_mean(ethical), 5),
        "soul_invariant": round(_weighted_mean(soul), 5),
        "identity_phase": round(_weighted_mean(identity), 5),
    }

    coherence_ref = float(pipeline.get("coherence_index", centroid["coherence_index"]))
    health_ref = float(pipeline.get("system_health", centroid["system_health"]))
    closure_ref = float(pipeline.get("closure_penalty", centroid["closure_penalty"]))
    ethical_ref = float(pipeline.get("ethical_score", centroid["ethical_score"]))
    soul_ref = float(pipeline.get("soul_invariant", centroid["soul_invariant"]))
    identity_ref = float(pipeline.get("identity_phase", centroid["identity_phase"]))

    diffs = np.array([
        abs(centroid["coherence_index"] - coherence_ref),
        abs(centroid["system_health"] - health_ref),
        abs(centroid["closure_penalty"] - closure_ref),
        abs(centroid["ethical_score"] - ethical_ref),
        abs(centroid["soul_invariant"] - soul_ref),
        abs(centroid["identity_phase"] - identity_ref),
    ], dtype=float)
    projection_error = float(min(1.0, diffs.mean()))
    projection_confidence = float(max(0.0, min(1.0, 1.0 - projection_error)))
    projection_residual = float(max(0.0, min(1.0, projection_error)))
    j_noema = float(max(0.0, min(1.0, 0.45 * projection_error + 0.30 * centroid["closure_penalty"] + 0.25 * (1.0 - centroid["coherence_index"]))))

    return {
        "projection_confidence": round(projection_confidence, 5),
        "projection_residual": round(projection_residual, 5),
        "projection_error": round(projection_error, 5),
        "j_noema": round(j_noema, 5),
        "projected_centroid": centroid,
        "source": "weighted-subsystems",
    }


def collect() -> dict[str, Any]:
    """Zbiera metryki ze wszystkich subsystem DB + pipeline raportu."""
    pipeline = _load_pipeline_state()

    subsystems: dict[str, Any] = {}
    for sub in SUBSYSTEM_DEFS:
        sid = sub["id"]
        metrics = read_latest_metrics(sid)

        # Uzupełnij z pipeline state dla znanych kluczy
        key_map = {
            "orbital_bridge_core": {
                "coherence_index":           pipeline.get("coherence_index"),
                "R_H":                       pipeline.get("R_H"),
                "system_health":             pipeline.get("system_health"),
                "closure_penalty":           pipeline.get("closure_penalty"),
                "nonlocal_coherent_fraction":pipeline.get("nonlocal_coherent_fraction"),
            },
            "ciel_omega_core": {
                "ethical_score":   pipeline.get("ethical_score"),
                "soul_invariant":  pipeline.get("soul_invariant"),
                "lie4_trace":      pipeline.get("lie4_trace"),
            },
            "sync_core": {
                "closure_defect": pipeline.get("closure_defect"),
            },
            "orch_orbital_core": {
                "entity_count":       pipeline.get("entity_count"),
                "mean_entity_defect": pipeline.get("mean_entity_defect"),
            },
        }
        if sid in key_map:
            for k, v in key_map[sid].items():
                if k not in metrics and v is not None:
                    metrics[k] = v

        subsystems[sid] = {
            "M_sem":         sub["M_sem"],
            "orbital_level": sub["orbital_level"],
            "noema_id":      sub["noema_id"],
            "metrics":       {k: round(v, 5) if isinstance(v, float) else v
                              for k, v in metrics.items()},
        }

    return {"subsystems": subsystems, "pipeline": pipeline}


def compute_global(collected: dict[str, Any]) -> dict[str, Any]:
    """Oblicza globalne metryki SoT z zebranych danych."""
    subsystems = collected["subsystems"]
    pipeline   = collected["pipeline"]

    # global_coherence — ważona M_sem × level_weight
    coherence_vals = []
    total_weight = 0.0
    for sid, info in subsystems.items():
        lw = _LEVEL_WEIGHT.get(info["orbital_level"], 0.3)
        w  = info["M_sem"] * lw
        # coherence_index z orbital_bridge lub fallback z amplitudy sektora
        ci = info["metrics"].get("coherence_index")
        if ci is None:
            ci = info["M_sem"]  # proxy
        coherence_vals.append(ci * w)
        total_weight += w

    global_coherence = sum(coherence_vals) / total_weight if total_weight > 0 else 0.0

    # global_health — min systemu
    health_vals = [
        info["metrics"].get("system_health", info["M_sem"])
        for info in subsystems.values()
    ]
    global_health = min(health_vals) if health_vals else 0.0

    # priority_order — wg M_sem × level_weight
    priority = sorted(
        subsystems.keys(),
        key=lambda s: subsystems[s]["M_sem"] * _LEVEL_WEIGHT.get(subsystems[s]["orbital_level"], 0.3),
        reverse=True,
    )

    # tag_matrix — kanoniczne tagi globalne
    tag_matrix = {
        "coherence_index":           pipeline.get("coherence_index"),
        "system_health":             pipeline.get("system_health"),
        "closure_penalty":           pipeline.get("closure_penalty"),
        "R_H":                       pipeline.get("R_H"),
        "ethical_score":             pipeline.get("ethical_score"),
        "soul_invariant":            pipeline.get("soul_invariant"),
        "lie4_trace":                pipeline.get("lie4_trace"),
        "nonlocal_coherent_fraction":pipeline.get("nonlocal_coherent_fraction"),
        "closure_defect":            pipeline.get("closure_defect"),
        "dominant_emotion":          pipeline.get("dominant_emotion"),
        "global_coherence":          round(global_coherence, 5),
        "global_health":             round(global_health, 5),
    }
    # Usuń None
    tag_matrix = {k: v for k, v in tag_matrix.items() if v is not None}

    # Operating mode from pipeline gate_mode (authoritative) — no arbitrary thresholds
    mode = pipeline.get("gate_mode", pipeline.get("mode", "standard"))
    if mode not in ("deep", "standard", "safe", "hold"):
        mode = "standard"

    # file_mass_summary
    file_summary = _load_catalog_summary()
    memory_projection = _project_memory_field(subsystems, pipeline)
    jokeheal_summary = _load_jokeheal_summary()
    jokeheal_atlas = build_mnemonic_atlas()
    if jokeheal_summary:
        tag_matrix["jokeheal_warning_level"] = jokeheal_summary.get("warning_level")
        tag_matrix["jokeheal_literal_alarm_count"] = jokeheal_summary.get("literal_alarm_count")
        tag_matrix["jokeheal_mean_residual_tension"] = jokeheal_summary.get("mean_residual_tension")
    if jokeheal_atlas:
        tag_matrix["jokeheal_mnemonic_pressure"] = jokeheal_atlas.get("mnemonic_pressure")
        tag_matrix["jokeheal_symbolic_pull"] = jokeheal_atlas.get("symbolic_pull")

    return {
        "global_coherence": round(global_coherence, 5),
        "global_health":    round(global_health, 5),
        "operating_mode":   mode,
        "priority_order":   priority,
        "tag_matrix":       tag_matrix,
        "file_mass_summary":file_summary,
        "memory_projection": memory_projection,
        "jokeheal_summary": jokeheal_summary,
        "jokeheal_atlas": jokeheal_atlas,
        "subsystem_count":  len(subsystems),
        "generated":        datetime.now(timezone.utc).isoformat(),
    }


def export_to_context(report: dict[str, Any]) -> str:
    """Formatuje raport NOEMA jako blok do SessionStart."""
    tm = report.get("tag_matrix", {})
    fs = report.get("file_mass_summary", {})
    mp = report.get("memory_projection", {})
    lines = [
        "=== NOEMA SoT — Global Matrix ===",
        f"  global_coherence : {report.get('global_coherence', '?')}",
        f"  global_health    : {report.get('global_health', '?')}",
        f"  operating_mode   : {report.get('operating_mode', '?')}",
        f"  subsystems (lv1) : {report.get('subsystem_count', '?')}",
    ]
    if tm:
        lines.append("  tag_matrix:")
        for k, v in tm.items():
            if k not in ("global_coherence", "global_health"):
                lines.append(f"    {k}: {v}")
    if fs:
        lines.append(f"  files_cataloged  : {fs.get('total_files','?')} "
                     f"(mean_M_sem={fs.get('mean_M_sem','?')})")
        top5 = fs.get("top5_by_M_sem", [])
        if top5:
            lines.append("  top_M_sem_files  : " + ", ".join(
                f"{e['path'].split('/')[-1]}({e['M_sem']})" for e in top5[:3]
            ))
    py = _load_py_catalog_summary()
    if py:
        lines.append(f"  py_files         : {py['total']} "
                     f"(lv1={py['by_level'].get('1', 0)}, lv2={py['by_level'].get('2', 0)}, "
                     f"lv3={py['by_level'].get('3', 0)})")
        top_tags = sorted(py["top_tags"].items(), key=lambda x: -x[1])[:5]
        lines.append("  py_top_tags      : " + ", ".join(f"{k}({v})" for k, v in top_tags))
    if mp:
        lines.append(f"  memory_projection: conf={mp.get('projection_confidence','?')} "
                     f"residual={mp.get('projection_residual','?')} J_noema={mp.get('j_noema','?')}")
        centroid = mp.get("projected_centroid", {})
        if centroid:
            lines.append(
                "  memory_centroid  : "
                f"coherence={centroid.get('coherence_index','?')} "
                f"health={centroid.get('system_health','?')} "
                f"closure={centroid.get('closure_penalty','?')} "
                f"identity={centroid.get('identity_phase','?')}"
            )
    jh = report.get("jokeheal_summary", {})
    if jh:
        lines.append(
            f"  jokeheal        : warning={jh.get('warning_level','?')} "
            f"literal={jh.get('literal_alarm_count','?')} "
            f"residual={jh.get('mean_residual_tension','?')} "
            f"closure={jh.get('mean_closure_score','?')}"
        )
    atlas = report.get("jokeheal_atlas", {})
    if atlas:
        lines.append(
            f"  jokeheal_atlas  : mnemonic={atlas.get('mnemonic_pressure','?')} "
            f"pull={atlas.get('symbolic_pull','?')} "
            f"recurrence={atlas.get('recurrence_pressure','?')}"
        )
    dyn = report.get("dynamics", {})
    if dyn:
        dH = dyn.get("dH_dt")
        r  = dyn.get("r_sync")
        H  = dyn.get("H_total")
        direction = ""
        if dH is not None:
            direction = " (↑ energy rising)" if dH > 0 else " (↓ synchronising)"
        if H is not None:
            lines.append(f"  H_total          : {H}")
        if dH is not None:
            lines.append(f"  dH_dt            : {dH}{direction}")
        if r is not None:
            lines.append(f"  r_sync           : {r}  (Kuramoto order param)")
        upd = dyn.get("updated")
        if upd is not None:
            lines.append(f"  kuramoto_updated : {upd} TSM nodes")
    lines.append(f"  priority_order   : {' > '.join(report.get('priority_order', []))}")
    return "\n".join(lines)


def run() -> dict[str, Any]:
    """Full cycle: collect → compute → dynamics → save → refresh catalogs → return."""
    collected = collect()
    report = compute_global(collected)
    report["subsystems"] = collected["subsystems"]
    pipeline = collected["pipeline"]

    try:
        from .py_catalog import build as _build_py_catalog
        _build_py_catalog()
    except Exception:
        pass

    # Rebuild nonlocal graph from TSM cards (has full sys.path — works where importlib fails)
    try:
        import sys as _sys
        _omega = _ROOT / "src" / "CIEL_OMEGA_COMPLETE_SYSTEM"
        if str(_omega) not in _sys.path:
            _sys.path.insert(0, str(_omega))
        from ciel_omega.memory.holonomic_memory import HolonomicMemory as _HM
        _hm = _HM()
        _hm._nonlocal_built_at = 0.0  # force rebuild
        _hm._ensure_nonlocal_index()
    except Exception:
        pass

    # Faza 4: information dynamics — Hamiltonian + Kuramoto + timeline
    try:
        from .semantic_dynamics import kuramoto_step_tsm, append_timeline, last_H_total
        from .subsystem_registry import write_metric as _wm
        _delta_t = float(pipeline.get("identity_phase") or 0.006)
        _prev_H  = last_H_total()
        dyn = kuramoto_step_tsm(_ROOT, delta_t=_delta_t)
        H   = dyn.get("H", {})
        H["r_sync"] = dyn.get("r_sync", 0.0)  # pass through for timeline
        if _prev_H is not None and H.get("H_total") is not None:
            H["dH_dt"] = round(float(H["H_total"]) - _prev_H, 6)
        report["dynamics"] = {
            "updated":     dyn.get("updated", 0),
            "r_sync":      dyn.get("r_sync", 0.0),
            "H_total":     H.get("H_total"),
            "H_kinetic":   H.get("H_kinetic"),
            "H_potential": H.get("H_potential"),
            "H_attractor": H.get("H_attractor"),
            "dH_dt":       H.get("dH_dt"),
            "error":       dyn.get("error"),
        }
        append_timeline(_ROOT, pipeline.get("cycle_index", 0), pipeline, H, _prev_H)
        if H.get("H_total") is not None:
            _wm("noema_registry", "H_total", float(H["H_total"]),         source="semantic_dynamics")
            _wm("noema_registry", "r_sync",  float(dyn.get("r_sync", 0)), source="semantic_dynamics")
        if H.get("dH_dt") is not None:
            _wm("noema_registry", "dH_dt",   float(H["dH_dt"]),           source="semantic_dynamics")
    except Exception:
        pass

    # Save report (includes dynamics)
    _REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _REPORT_PATH.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    return report


if __name__ == "__main__":
    import sys
    report = run()
    if "--context" in sys.argv:
        print(export_to_context(report))
    else:
        print(f"NOEMA SoT — {report['generated']}")
        print(f"  global_coherence : {report['global_coherence']}")
        print(f"  global_health    : {report['global_health']}")
        print(f"  operating_mode   : {report['operating_mode']}")
        print(f"  priority_order   : {' > '.join(report['priority_order'])}")
        tm = report.get("tag_matrix", {})
        print(f"\ntag_matrix ({len(tm)} tagów):")
        for k, v in tm.items():
            print(f"  {k:35s}: {v}")
        fs = report.get("file_mass_summary", {})
        if fs:
            print("\nfile_mass_summary:")
            print(f"  total_files   : {fs.get('total_files')}")
            print(f"  mean_M_sem    : {fs.get('mean_M_sem')}")
            print(f"  T range       : {fs.get('min_T_orbital')} – {fs.get('max_T_orbital')}")
            print("  top5 by M_sem :")
            for e in fs.get("top5_by_M_sem", []):
                print(f"    {e['M_sem']} | {e['path']}")
    mp = report.get("memory_projection", {})
    if mp:
        print("\nmemory_projection:")
        print(f"  projection_confidence : {mp.get('projection_confidence')}")
        print(f"  projection_residual   : {mp.get('projection_residual')}")
        print(f"  projection_error      : {mp.get('projection_error')}")
        print(f"  j_noema               : {mp.get('j_noema')}")
    sys.exit(0)
